controllers:
    resource: ../src/Controller/
    type: attribute

index:
    path: /contrat
    controller: App\Controller\ContratController::index

contratLister:
    path: /contrat/lister
    controller: App\Controller\ContratController::contratLister

consulterContrat:
    path : /contrat/consulter/{id}
    controller : App\Controller\ContratController::consulterContrat

interventionLister:
    path: /intervention/lister
    controller: App\Controller\InterventionController::interventionLister

consulterIntervention:
    path: /intervention/consulter/{id}
    controller: App\Controller\InterventionController::consulterIntervention

ajouterContrat:
    path: /contrat/ajouter
    controller: App\Controller\ContratController::ajouterContrat