controllers:
    resource: ../src/Controller/
    type: attribute

index:
    path: /
    controller: App\Controller\IndexController::index

login:
    path : /login
    controller: App\Controller\SecurityController::login

logout:
    path : /logout
    methods: GET

register:
    path: /register
    controller: App\Controller\RegistrationController::register

panel:
    path: /panel
    controller: App\Controller\InstrumentController::lister

contratLister:
    path: /gestionnaire/contrat/lister
    controller: App\Controller\ContratController::contratLister

contratListerParInstrument:
    path: /gestionnaire/contrat/lister/{id}
    controller: App\Controller\ContratController::contratListerParInstrument

consulterContrat:
    path : /eleve/contrat/consulter/{id}
    controller : App\Controller\ContratController::consulterContrat

interventionLister:
    path: /gestionnaire/intervention/lister/{id}
    controller: App\Controller\InterventionController::listerByInstrument

consulterIntervention:
    path: /eleve/intervention/consulter/{id}
    controller: App\Controller\InterventionController::consulterIntervention

ajouterContrat:
    path: /gestionnaire/contrat/ajouter
    controller: App\Controller\ContratController::ajouterContrat

ContratModifier:
    path: /gestionnaire/contrat/modifier/{id}
    controller:  App\Controller\ContratController::ContratModifier

coursLister:
    path: /eleve/cours/lister
    controller: App\Controller\CoursController::lister

coursConsulter:
    path: /eleve/cours/consulter/{id}
    controller: App\Controller\CoursController::consulter

coursAjouter:
    path: /gestionnaire/cours/ajouter
    controller: App\Controller\CoursController::ajouter

coursModifier:
    path: /gestionnaire/cours/modifier/{id}
    controller: App\Controller\CoursController::modifier
    
listerAccessoire:
    path: /gestionnaire/accessoire/lister
    controller: App\Controller\AccessoireController::lister

listerInstrument:
    path: /gestionnaire/instrument/lister
    controller: App\Controller\InstrumentController::lister

listerInstrumentByUser:
    path: /eleve/instrument/listerByUser
    controller: App\Controller\InstrumentController::listerByUser

consulterInstrument:
    path: /eleve/instrument/consulter/{id}
    controller: App\Controller\InstrumentController::consulter

ajouterInstrument:
    path: /gestionnaire/instrument/ajouter
    controller: App\Controller\InstrumentController::ajouter

modifierInstrument:
    path: /gestionnaire/instrument/modifier/{id}
    controller: App\Controller\InstrumentController::modifier


professeurLister:
    path: /gestionnaire/professeur/lister
    controller: App\Controller\ProfesseurController::lister

professeurConsulter:
    path: /gestionnaire/professeur/consulter/{id}
    controller: App\Controller\ProfesseurController::consulter

professeurAjouter:
    path: /gestionnaire/professeur/ajouter
    controller: App\Controller\ProfesseurController::ajouter

modifierProfesseur:
    path: /gestionnaire/professeur/modifier/{id}
    controller: App\Controller\ProfesseurController::modifier

ajouterIntervention:
    path: /gestionnaire/intervention/ajouter
    controller: App\Controller\InterventionController::ajouterIntervention
    
app_intervention_ajouter:
    path: /gestionnaire/intervention/ajouter/{instrumentId}
    controller: App\Controller\InterventionController::ajouterIntervention

modifierIntervention:
    path: /gestionnaire/intervention/modifier/{id}
    controller: App\Controller\InterventionController::modifierIntervention

ajax_add_accessory:
    path: /ajax/add-accessory
    methods: post
    controller: App\Controller\AccessoireController::ajaxAddAccessory

ajax_del_accessory:
    path: /ajax/del-accessory
    methods: post
    controller: App\Controller\AccessoireController::ajaxDelAccessory
    
eleveLister:
    path: /admin/eleve/lister
    controller: App\Controller\EleveController::lister

eleveConsulter:
    path: /admin/eleve/consulter/{id}
    controller: App\Controller\EleveController::consulter

eleveAjouter:
    path: /admin/eleve/ajouter
    controller: App\Controller\EleveController::ajouter

eleveModifier:
    path: /admin/eleve/modifier/{id}
    controller: App\Controller\EleveController::modifier
