controllers:
    resource: ../src/Controller/
    type: attribute

coursLister:
    path: /cours/lister
    controller: App\Controller\CoursController::lister

coursConsulter:
    path: /cours/consulter/{id}
    controller: App\Controller\CoursController::consulter