controllers:
    resource: ../src/Controller/
    type: attribute

instrument:
    path: /instrument/
    controller: App\Controller\InstrumentController::index

listerInstrument:
    path: /instrument/lister
    controller: App\Controller\InstrumentController::lister