controllers:
    resource: ../src/Controller/
    type: attribute

index:
    path: /
    controller: App\Controller\IndexController::index

register:
    path: /register
    controller: App\Controller\IndexController::register

panel:
    path: /panel
    controller: App\Controller\InstrumentController::lister

contrat:
    path: /contrat
    controller: App\Controller\ContratController::index

contratLister:
    path: /contrat/lister
    controller: App\Controller\ContratController::contratLister

consulterContrat:
    path : /contrat/consulter/{id}
    controller : App\Controller\ContratController::consulterContrat

interventionLister:
    path: /intervention/lister/{id}
    controller: App\Controller\InterventionController::listerByInstrument

consulterIntervention:
    path: /intervention/consulter/{id}
    controller: App\Controller\InterventionController::consulterIntervention

ajouterContrat:
    path: /contrat/ajouter
    controller: App\Controller\ContratController::ajouterContrat

ContratModifier:
    path: /contrat/modifier/{id}
    controller:  App\Controller\ContratController::ContratModifier

coursLister:
    path: /cours/lister
    controller: App\Controller\CoursController::lister

coursConsulter:
    path: /cours/consulter/{id}
    controller: App\Controller\CoursController::consulter

coursAjouter:
    path: /cours/ajouter
    controller: App\Controller\CoursController::ajouter

coursModifier:
    path: /cours/modifier/{id}
    controller: App\Controller\CoursController::modifier
    
listerAccessoire:
    path: /accessoire/lister
    controller: App\Controller\AccessoireController::lister

listerInstrument:
    path: /instrument/lister
    controller: App\Controller\InstrumentController::lister

consulterInstrument:
    path: /instrument/consulter/{id}
    controller: App\Controller\InstrumentController::consulter

ajouterInstrument:
    path: /instrument/ajouter
    controller: App\Controller\InstrumentController::ajouter

modiferInstrument:
    path: /instrument/modifier/{id}
    controller: App\Controller\InstrumentController::modifier


professeurLister:
    path: /professeur/lister
    controller: App\Controller\ProfesseurController::lister

professeurConsulter:
    path: /professeur/consulter/{id}
    controller: App\Controller\ProfesseurController::consulter

professeurAjouter:
    path: /professeur/ajouter
    controller: App\Controller\ProfesseurController::ajouter

modifierProfesseur:
    path: /professeur/modifier/{id}
    controller: App\Controller\ProfesseurController::modifier

ajouterIntervention:
    path: /intervention/ajouter
    controller: App\Controller\InterventionController::ajouterIntervention