controllers:
    resource: ../src/Controller/
    type: attribute

coursLister:
    path: /cours/lister
    controller: App\Controller\CoursController::lister

coursConsulter:
    path: /cours/consulter/{id}
    controller: App\Controller\CoursController::consulter

coursAjouter:
    path: /cours/ajouter
    controller: App\Controller\CoursController::ajouter

coursModifier:
    path: /cours/modifier/{id}
    controller: App\Controller\CoursController::modifier
    
instrument:
    path: /instrument/
    controller: App\Controller\InstrumentController::index

listerInstrument:
    path: /instrument/lister
    controller: App\Controller\InstrumentController::lister

consulterInstrument:
    path: /instrument/consulter/{id}
    controller: App\Controller\InstrumentController::consulter

ajouterInstrument:
    path: /instrument/ajouter
    controller: App\Controller\InstrumentController::ajouter

modiferInstrument:
    path: /instrument/modifier/{id}
    controller: App\Controller\InstrumentController::modifier

professeurLister:
    path: /professeur/lister
    controller: App\Controller\ProfesseurController::lister

professeurConsulter:
    path: /professeur/consulter/{id}
    controller: App\Controller\ProfesseurController::consulter

professeurAjouter:
    path: /professeur/ajouter
    controller: App\Controller\ProfesseurController::ajouter

modifierProfesseur:
    path: /professeur/modifier/{id}
    controller: App\Controller\ProfesseurController::modifier
