controllers:
    resource: ../src/Controller/
    type: attribute

index:
    path: /contrat
    controller: App\Controller\ContratController::index

contratLister:
    path: /contrat/lister
    controller: App\Controller\ContratController::contratLister

consulterContrat:
    path : /contrat/consulter/{id}
    controller : App\Controller\ContratController::consulterContrat

